### ISSUE TITLE
[Q] hierarchy representations

### ISSUE THREAD

**Issue by PARODBE** [UCLCheminformatics/ScaffoldGraph#20]
## ❓ Questions & Help

Hi,

Thanks for this so useful library...I have a doubt, when you are building a hierarchy representation, each bar represent the times of one scaffold is repeated in a dataset??? For example in your example: https://github.com/UCLCheminformatics/ScaffoldGraph/blob/master/examples/scaffold_graphs.ipynb    for a network representation. How I could the molecule for earch hierarchy class? I want Know the scaffolds most repeated in the dataset.

Thanks!

Pablo

**Comment by OliverBScott** [comment]
Hi Pablo,

In the example notebook, the bars represent the number of (unique) scaffolds in each hierarchy (i.e. scaffolds in hierarchy 2 would all contain 2 rings). These scaffolds may be the parent scaffold for multiple molecules in the dataset. If you would like to find the scaffolds which are most common in the dataset you can count the number of molecules each scaffold is a parent of. This is fairly straightforward:

```python
# First add attribute 'count' to each scaffold with the number of molecules it represents.
network.add_scaffold_molecule_count()

# Next return scaffolds sorted by the number of molecules they represent.
most_common = sorted(network.get_scaffold_nodes('count'), key=lambda x: x[1], reverse=True)

# Print the top 5 most common.
print(most_common[:5])
```

Often you may want to limit this to a particular hierarchy (hierarchy 1 may not be as useful as 2 and above).

```python
# Get the most common scaffolds in hierarchy 2.
most_common_2 = sorted(network.get_scaffolds_in_hierarchy(2, 'count'), key=lambda x: x[1], reverse=True)

# Print the top 5 most common.
print(most_common_2[:5])
```

Hope this helps!

Oliver

**Comment by PARODBE** [comment]
Hi Oliver!

Thank you very much!!! This is exactly that I need!

Thanks!

Pablo

**Comment by PARODBE** [comment]
Hi again Oliver,

It is very curious, look at please:

![image](https://user-images.githubusercontent.com/62376157/112632899-fe424200-8e38-11eb-85d6-28df9d2a16f8.png)

I select the first elemen for hierarchy 2, and the count is 10, ok? If after, I use this:

![image](https://user-images.githubusercontent.com/62376157/112633053-29c52c80-8e39-11eb-95f6-f0b79df1dc3d.png)

The number of molecules for hierarchy 2 which contain this structure is 8 and not 10, why are not they matching?

Thanks!
Pablo

**Comment by OliverBScott** [comment]
Hi Pablo,

In the first example, the number 10 corresponds to the number of molecules represented by that particular scaffold. We can also see this like so:

```python
print(len(network.get_molecules_for_scaffold('O=c1ccc2ccccc2o1')))
>>> 10
```
In the second example, the traversal is in the opposite direction child -> parent (scaffold -> scaffold). Here the code is getting scaffolds in the next scaffold hierarchy from the query (2 -> 3).  Admittedly here I have made a typo, the code should say that it is finding scaffolds in hierarchy 3 rather than 2 (I will change this at some point). So in this case the scaffold `O=c1ccc2ccccc2o1` (hierarchy 2) corresponds to 10 molecules in the dataset and is a parent of 8 scaffolds in the next hierarchy. I hope this makes sense!

Here is an illustration, darker shades of blue indicate a higher hierarchy:

![Screen Shot 2021-03-26 at 13 21 25](https://user-images.githubusercontent.com/33868948/112637665-4f046b80-8e36-11eb-909c-69ad5d0e6ea8.png)

**Comment by PARODBE** [comment]
Ok, now I have understood! Thanks!! I thought that is possible that the next number would be 8 but my molecule is 10! hehe ok is clear now, please when you change this part if you could notify...I have enjoyed with your code! It is amazing!

Thanks for all Oliver.

Pablo

**Comment by OliverBScott** [comment]
Great! I am glad you are enjoying the code. 

I just checked for the typo and the notebook is actually correct as it uses the scaffold `c1ccncc1` rather than `O=c1ccc2ccccc2o1`. So the hierarchy change, in this case, is 1->2 rather than 2->3, but the idea is the same.
