### ISSUE TITLE
Is it possible to generate Chemical Space Networks [Q]

### ISSUE THREAD

**Issue by syedzayyan** [UCLCheminformatics/ScaffoldGraph#24]
## ❓ Questions & Help

Basically the title, something like this->

<img width="580" alt="Screenshot 2023-08-22 at 14 20 48" src="https://github.com/UCLCheminformatics/ScaffoldGraph/assets/44922710/1901135c-8799-4afe-a488-189dfd022723">

The picture is taken from (https://jcheminf.biomedcentral.com/articles/10.1186/s13321-022-00664-x)

Thanks

**Comment by OliverBScott** [comment]
Hi! currently there is no built-in method to generate this style of plot, but it should be relatively straightforward to follow the [notebooks provided by this paper ](https://github.com/vfscalfani/CSN_tutorial/blob/main/CSN_Jupyter_Notebooks/CSN_glucocorticoid_MCS_2.ipynb). You should be able to almost follow it directly since the graph we use is a networkx graph under the hood. If you specify properties when building, or your sdf file contains properties these will be available on the molecule nodes. If you are using jupyter we do have a [visualisation tool based on cytoscape](https://github.com/UCLCheminformatics/ScaffoldGraph/blob/main/scaffoldgraph/vis/notebook/cytoscape.py).

It would be nice to have a networkx based visualisation tool built-in, I would be happy to accept PRs :)

**Comment by syedzayyan** [comment]
networkx representation falter down when dealing with 4000 compounds that are very related which I am dealing with at the moment, unfortunately. I did try the notebooks from that paper. 

I get that. :)

![image](https://github.com/UCLCheminformatics/ScaffoldGraph/assets/44922710/8a96c53e-3d1c-4ab6-ba77-d924f181edd1)

![image](https://github.com/UCLCheminformatics/ScaffoldGraph/assets/44922710/07b15d2e-db58-49ba-b3c8-360f517bc42f)

But I'll try something with graphviz, instead of networkx if thats allowed.

**Comment by OliverBScott** [comment]
I think graph visualisation is always going to be tricky when nodes are highly interconnected. It might be interesting to try something like bundling nodes together that are linked and share a similar property value. At one point I was also looking at visualisations like [circle packing/treemaps](https://d3js.org/d3-hierarchy/pack), but of course these would only work with the scaffold-tree. 

Would also be happy to accept PRs for a graphviz based solution :)
